### ISSUE TITLE
automatic git blame after line change

### ISSUE THREAD

**Issue by Salomanuel** [zivyangll/git-blame.vim#20]
it would be awesome if the `git blame` output would be automatically displayed every time the line changes, maybe with some delay to not decrease performance

in a similar way VisualStudioCode does or even other plugins for neoVim (https://github.com/APZelos/blamer.nvim)

**Comment by Edo78** [comment]
Something like `:autocmd CursorMoved * :call gitblame#echo()` ?

**Comment by wotzhs** [comment]
this is probably too late, I also stumbled upon this question, _i think_ `CursorHold` is a _better_ option compared to `CursorMoved`

**Comment by Edo78** [comment]
The right answer is never too late

**Comment by ebiscaia** [comment]
Hi guys,

Is it possible to add this to the main page and how could I toggle on/off?

Cheers
