### ISSUE TITLE
E117: Unknown function: gitblame#echo

### ISSUE THREAD

**Issue by snevs** [zivyangll/git-blame.vim#21]
I followed the install instructions and when I go to a file and try the \s comand, it throws this error:

E117: Unknown function: gitblame#echo
![image](https://user-images.githubusercontent.com/18164031/76849083-67b66a80-684d-11ea-9210-e32386b63652.png)

**Comment by mik13ST** [comment]
What shell are you using (`echo $SHELL`)? I am having similar problems recently on Fish shell. On Bash this plugin works fine. Could you try it on Bash?

```
SHELL=/usr/bin/bash vim
```

My problems started after I recently updated my Vim plugins.

**Comment by pacoard** [comment]
I'm also having this issue, even after trying out SHELL=/usr/bin/bash vim 😢

**Comment by jazzyfresh** [comment]
Hi, I am experiencing this on bash, anyone find a workaround or tips to debug?

Probably something with my setup... I am on a Mac, which sets zsh as default shell but i configured it to use bash. I did have to `export SHELL=/bin/bash` since I guess Terminal didn't set that correctly
